server:
  port: 4553

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: WA post deployment functional test
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          oidc:
            client-id: ${WA_IDAM_CLIENT_ID}
            client-secret: ${WA_IDAM_CLIENT_SECRET}
azure:
  application-insights:
    instrumentation-key: ${wa.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

idam:
  baseUrl: ${WA_IDAM_URL}
  redirectUrl: ${WA_IDAM_REDIRECT_URI}
  scope: "openid profile roles"
  s2s-auth:
    url: ${S2S_URL}
    secret: ${S2S_SECRET_TASK_MANAGEMENT_API}
    name: ${S2S_NAME_TASK_MANAGEMENT_API}
  api:
    baseUrl: ${WA_IDAM_URL}
  test:
    userCleanupEnabled: ${ENABLE_TEST_USER_DELETION}

camunda:
  url: ${CAMUNDA_URL}

role-assignment-service:
  url: ${ROLE_ASSIGNMENT_URL}

logging:
  level:
    com.azure.*: OFF
    com.azure.core.amqp.implementation.*: OFF
    net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated: DEBUG

environment:
  dummy:
